1. Challenge 1:
  - Answer : B
  - Explanation: It is answer B because the variable takes the value XYZ within the function, after that the function is executed and shows the value of the variable, and finally a console.log of the variable is made. 


2. Challenge 2:
  - Answer : C
  - Explanation: It's answer C because, despite the variable taking different values ​​from the function, there are 2 console.Log, the first writes the value it has inside the function, the second the value it has outside


3. Challenge 3: 
  - Answer : A
  - Explanation: is answer A, because when sayHi is executed the function has not yet been created and it gives an error.


4. Challenge 4:
  - Answer : C
  - Explanation: is the answer C because the Num property is changed to 90 and as b is equal to a it is also assumed in A.


5. Bonus - Challenge 5:
  - Answer :
  - Explanation:
